server:
  port: 8020

spring:
  application:
    name: kotlin-api
  config:
    import: "optional:configserver:http://localhost:8888"

  jpa:
    open-in-view: false

  data:
    web:
      pageable:
        default-page-size: 25

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  use-fqn: true
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    doc-expansion: none

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [${spring.application.name:}, traceId:%X{traceId:-}, spanId:%X{spanId:-}] %-5level [%thread] %logger{36} - %msg%n"
